Templating
gentoo/cargo-ebuild pull request #10
Opened 2021-07-29 14:32 UTC by lu-zero

- [x] Convert the current template to tera
- [x] Add and option to pass a custom template
- [ ] Refactor the template in a `base.tera` with good defaults and let the user rely on it
- [ ] Document everything

2021-07-29 18:37 UTC, gyakovlev requested changes
left some  template comments.
also, can you sign-off commits please?
it's required for gentoo namespace.
I've added a github check for it btw.

2021-07-29 18:37 UTC, gyakovlev commented on src/base.tera
> +# Copyright 2017-{{ this_year }} Gentoo Authors
just leave current year, it's ok for new ebuilds.

2021-07-29 18:37 UTC, gyakovlev commented on src/base.tera
> +EAPI={%- block eapi -%}7{%- endblock %}
let's use `8` by default.

2021-07-29 18:37 UTC, gyakovlev commented on src/base.tera
> +SRC_URI={%- block src_uri -%}{% raw -%}"$(cargo_crate_uris ${CRATES})"{%- endraw %}{%- endblock %}
let's use  just `$(cargo_crate_uris)` as it automagically uses $CRATES nowadays, passing is optional.

2021-07-29 18:37 UTC, gyakovlev commented on src/base.tera
> +RESTRICT="mirror"
this restriction is ok and makes sense for overlays, but is discouraged for `::gentoo`
but I can edit the template later and add a simple comment that users should maybe remove it if ebuild is for main repo.

2021-08-05 10:01 UTC, lu-zero commented
I rebased and updated the template according to your suggestion, let me know if it works for you.

2021-08-25 15:35 UTC, closed without merging